name: test

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_call:

concurrency:
  group: 'test-${{ github.ref_name }}'
  cancel-in-progress: true

env:
  APP_VERSION: ${{ format('0.0.0-build{0}', github.run_number) }}

jobs:
  bff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testsuite:
          - core
    steps:
      - uses: actions/checkout@v5
      - run: composer up:testing
      - run: composer paratest -- --processes=4 --testsuite ${{ matrix.testsuite }}
